(make-face 'calendar-today-face)
              (set-face-foreground 'calendar-today-face "Black")
              (set-face-background 'calendar-today-face "WhiteSmoke")
              (set-face-font 'calendar-today-face "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'font-lock-keyword-face)
              (set-face-foreground 'font-lock-keyword-face "Blue")
              (set-face-background 'font-lock-keyword-face "WhiteSmoke")
              (set-face-font 'font-lock-keyword-face "*-courier-bold-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'font-lock-doc-string-face)
              (set-face-foreground 'font-lock-doc-string-face "DeepPink")
              (set-face-background 'font-lock-doc-string-face "WhiteSmoke")
              (set-face-font 'font-lock-doc-string-face "*-courier-medium-o-*-*-*-140-*-*-*-*-*-*")
(make-face 'font-lock-comment-face)
              (set-face-foreground 'font-lock-comment-face "Purple")
              (set-face-background 'font-lock-comment-face "WhiteSmoke")
              (set-face-font 'font-lock-comment-face "*-courier-medium-o-*-*-*-140-*-*-*-*-*-*")
(make-face 'secondary-selection)
              (set-face-foreground 'secondary-selection "Black")
              (set-face-background 'secondary-selection "paleturquoise")
              (set-face-font 'secondary-selection "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'font-lock-string-face)
              (set-face-foreground 'font-lock-string-face "DeepPink")
              (set-face-background 'font-lock-string-face "WhiteSmoke")
              (set-face-font 'font-lock-string-face "*-courier-medium-o-*-*-*-140-*-*-*-*-*-*")
(make-face 'info-node)
              (set-face-foreground 'info-node "Black")
              (set-face-background 'info-node "WhiteSmoke")
              (set-face-font 'info-node "*-courier-bold-o-*-*-*-140-*-*-*-*-*-*")
(make-face 'modeline)
              (set-face-foreground 'modeline "Black")
              (set-face-background 'modeline "Gray75")
              (set-face-font 'modeline "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'highlight)
              (set-face-foreground 'highlight "Black")
              (set-face-background 'highlight "darkseagreen2")
              (set-face-font 'highlight "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'underline)
              (set-face-foreground 'underline "Black")
              (set-face-background 'underline "WhiteSmoke")
              (set-face-font 'underline "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'zmacs-region)
              (set-face-foreground 'zmacs-region "Black")
              (set-face-background 'zmacs-region "yellow")
              (set-face-font 'zmacs-region "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'x-face)
              (set-face-foreground 'x-face "black")
              (set-face-background 'x-face "white")
              (set-face-font 'x-face "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'right-margin)
              (set-face-foreground 'right-margin "Black")
              (set-face-background 'right-margin "WhiteSmoke")
              (set-face-font 'right-margin "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'message-headers)
              (set-face-foreground 'message-headers "blue")
              (set-face-background 'message-headers "WhiteSmoke")
              (set-face-font 'message-headers "*-courier-bold-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'paren-mismatch)
              (set-face-foreground 'paren-mismatch "Black")
              (set-face-background 'paren-mismatch "DeepPink")
              (set-face-font 'paren-mismatch "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'paren-match)
              (set-face-foreground 'paren-match "Black")
              (set-face-background 'paren-match "darkseagreen2")
              (set-face-font 'paren-match "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'font-lock-type-face)
              (set-face-foreground 'font-lock-type-face "DeepSkyBlue")
              (set-face-background 'font-lock-type-face "WhiteSmoke")
              (set-face-font 'font-lock-type-face "*-courier-medium-o-*-*-*-140-*-*-*-*-*-*")
(make-face 'font-lock-function-name-face)
              (set-face-foreground 'font-lock-function-name-face "RoyalBlue")
              (set-face-background 'font-lock-function-name-face "WhiteSmoke")
              (set-face-font 'font-lock-function-name-face "*-courier-bold-o-*-*-*-140-*-*-*-*-*-*")
(make-face 'diary-face)
              (set-face-foreground 'diary-face "red")
              (set-face-background 'diary-face "WhiteSmoke")
              (set-face-font 'diary-face "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'bold)
              (set-face-foreground 'bold "Black")
              (set-face-background 'bold "WhiteSmoke")
              (set-face-font 'bold "*-courier-bold-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'primary-selection)
              (set-face-foreground 'primary-selection "Black")
              (set-face-background 'primary-selection "gray")
              (set-face-font 'primary-selection "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'default)
              (set-face-foreground 'default "Black")
              (set-face-background 'default "WhiteSmoke")
              (set-face-font 'default "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'info-xref)
              (set-face-foreground 'info-xref "Black")
              (set-face-background 'info-xref "WhiteSmoke")
              (set-face-font 'info-xref "*-courier-bold-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'italic)
              (set-face-foreground 'italic "Black")
              (set-face-background 'italic "WhiteSmoke")
              (set-face-font 'italic "*-courier-medium-o-*-*-*-140-*-*-*-*-*-*")
(make-face 'left-margin)
              (set-face-foreground 'left-margin "Black")
              (set-face-background 'left-margin "WhiteSmoke")
              (set-face-font 'left-margin "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'message-highlighted-header-contents)
              (set-face-foreground 'message-highlighted-header-contents "black")
              (set-face-background 'message-highlighted-header-contents "whitesmoke")
              (set-face-font 'message-highlighted-header-contents "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'isearch)
              (set-face-foreground 'isearch "Black")
              (set-face-background 'isearch "paleturquoise")
              (set-face-font 'isearch "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'bold-italic)
              (set-face-foreground 'bold-italic "Black")
              (set-face-background 'bold-italic "WhiteSmoke")
              (set-face-font 'bold-italic "*-courier-bold-o-*-*-*-140-*-*-*-*-*-*")
(make-face 'message-cited-text)
              (set-face-foreground 'message-cited-text "Black")
              (set-face-background 'message-cited-text "WhiteSmoke")
              (set-face-font 'message-cited-text "*-courier-medium-o-*-*-*-140-*-*-*-*-*-*")
(make-face 'message-header-contents)
              (set-face-foreground 'message-header-contents "Black")
              (set-face-background 'message-header-contents "WhiteSmoke")
              (set-face-font 'message-header-contents "*-courier-medium-o-*-*-*-140-*-*-*-*-*-*")
(make-face 'paren-blink-off)
              (set-face-foreground 'paren-blink-off "WhiteSmoke")
              (set-face-background 'paren-blink-off "WhiteSmoke")
              (set-face-font 'paren-blink-off "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
(make-face 'holiday-face)
              (set-face-foreground 'holiday-face "Black")
              (set-face-background 'holiday-face "pink")
              (set-face-font 'holiday-face "*-courier-medium-r-*-*-*-140-*-*-*-*-*-*")
